apiVersion: apps/v1
kind: Deployment
metadata:
  name:  gx-deploy
  namespace: default
  labels:
    app:  gx
spec:
  selector:
    matchLabels:
      app: gx
  replicas: 2
  template:
    metadata:
      labels:
        app: gx
    spec:
      containers:
      - name:  gx
        image: gx_deploy:v15
        ports:
        - containerPort:  8080
          name:  gx-port
        env:
        - name: "branch"
          value: "dev"
      restartPolicy: Always
