apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gx-app
  namespace: default
spec:
  destination:
    namespace: default # 部署应用的命名空间
    server: https://kubernetes.default.svc # API Server 地址
  project: default # 项目名
  source:
    path: nginx # 资源文件路径
    repoURL: https://github.com/NASAJPLS/k3s_gitops.git # Git 仓库地址
    targetRevision: main # 分支名
