apiVersion: v1
kind: Service
metadata:
  name: sport02-service
  namespace: default
spec:
  selector:
    app: sport02
  type: ClusterIP # ClusterIP 指的是当前 Service 在 Kubernetes 集群内可以被所有 Kubernetes 资源发现，默认给这个 Service 分配一个集群内的网络。
  ports:
  - name: sport02
    port: 10180 # service 的端口，访问到 service 的 80 端口
    targetPort: 80 # Pod 的端口，派发到 Pod 的 80 端口